version: '3.8'

services:
  backend:
    build: ./backend
    container_name: resume-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - /home/ubuntu/models/onnx-model:/models/onnx-model
      - /home/ubuntu/models/onnx:/models/onnx
      - /home/ubuntu/models/gemma:/models/gemma
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - resume-network

  frontend:
    image: nginx:latest
    container_name: resume-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build/dist:/usr/share/nginx/html
      - ./frontend/build/dist/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge